require("ActivityDungeon1002_MiniStart_MidLatticeAniByName")

function GetActivityDungeon1002_MiniStart_MidRegionUis(ui)
  local uis = {}
  uis.Lattice1 = GetActivityDungeon1002_MiniStart_MidLatticeAniUis(ui:GetChild("Lattice1"))
  uis.Lattice2 = GetActivityDungeon1002_MiniStart_MidLatticeAniUis(ui:GetChild("Lattice2"))
  uis.Lattice3 = GetActivityDungeon1002_MiniStart_MidLatticeAniUis(ui:GetChild("Lattice3"))
  uis.Lattice4 = GetActivityDungeon1002_MiniStart_MidLatticeAniUis(ui:GetChild("Lattice4"))
  uis.Lattice5 = GetActivityDungeon1002_MiniStart_MidLatticeAniUis(ui:GetChild("Lattice5"))
  uis.Lattice6 = GetActivityDungeon1002_MiniStart_MidLatticeAniUis(ui:GetChild("Lattice6"))
  uis.Lattice7 = GetActivityDungeon1002_MiniStart_MidLatticeAniUis(ui:GetChild("Lattice7"))
  uis.Lattice8 = GetActivityDungeon1002_MiniStart_MidLatticeAniUis(ui:GetChild("Lattice8"))
  uis.Lattice9 = GetActivityDungeon1002_MiniStart_MidLatticeAniUis(ui:GetChild("Lattice9"))
  uis.Lattice10 = GetActivityDungeon1002_MiniStart_MidLatticeAniUis(ui:GetChild("Lattice10"))
  uis.Lattice11 = GetActivityDungeon1002_MiniStart_MidLatticeAniUis(ui:GetChild("Lattice11"))
  uis.Lattice12 = GetActivityDungeon1002_MiniStart_MidLatticeAniUis(ui:GetChild("Lattice12"))
  uis.Lattice13 = GetActivityDungeon1002_MiniStart_MidLatticeAniUis(ui:GetChild("Lattice13"))
  uis.Lattice14 = GetActivityDungeon1002_MiniStart_MidLatticeAniUis(ui:GetChild("Lattice14"))
  uis.Lattice15 = GetActivityDungeon1002_MiniStart_MidLatticeAniUis(ui:GetChild("Lattice15"))
  uis.Lattice16 = GetActivityDungeon1002_MiniStart_MidLatticeAniUis(ui:GetChild("Lattice16"))
  uis.Lattice17 = GetActivityDungeon1002_MiniStart_MidLatticeAniUis(ui:GetChild("Lattice17"))
  uis.Lattice18 = GetActivityDungeon1002_MiniStart_MidLatticeAniUis(ui:GetChild("Lattice18"))
  uis.Lattice19 = GetActivityDungeon1002_MiniStart_MidLatticeAniUis(ui:GetChild("Lattice19"))
  uis.Lattice20 = GetActivityDungeon1002_MiniStart_MidLatticeAniUis(ui:GetChild("Lattice20"))
  uis.Lattice21 = GetActivityDungeon1002_MiniStart_MidLatticeAniUis(ui:GetChild("Lattice21"))
  uis.Lattice22 = GetActivityDungeon1002_MiniStart_MidLatticeAniUis(ui:GetChild("Lattice22"))
  uis.Lattice23 = GetActivityDungeon1002_MiniStart_MidLatticeAniUis(ui:GetChild("Lattice23"))
  uis.Lattice24 = GetActivityDungeon1002_MiniStart_MidLatticeAniUis(ui:GetChild("Lattice24"))
  uis.Lattice25 = GetActivityDungeon1002_MiniStart_MidLatticeAniUis(ui:GetChild("Lattice25"))
  uis.Lattice26 = GetActivityDungeon1002_MiniStart_MidLatticeAniUis(ui:GetChild("Lattice26"))
  uis.Lattice27 = GetActivityDungeon1002_MiniStart_MidLatticeAniUis(ui:GetChild("Lattice27"))
  uis.Lattice28 = GetActivityDungeon1002_MiniStart_MidLatticeAniUis(ui:GetChild("Lattice28"))
  uis.Lattice29 = GetActivityDungeon1002_MiniStart_MidLatticeAniUis(ui:GetChild("Lattice29"))
  uis.Lattice30 = GetActivityDungeon1002_MiniStart_MidLatticeAniUis(ui:GetChild("Lattice30"))
  uis.Lattice31 = GetActivityDungeon1002_MiniStart_MidLatticeAniUis(ui:GetChild("Lattice31"))
  uis.root = ui
  return uis
end
